<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<RootNamespace>SkillTree</RootNamespace>
		<LangVersion>default</LangVersion>
		<IsPackable>false</IsPackable>
		<AssemblyVersion>2.6.5</AssemblyVersion>
		<NeutralLanguage>en-US</NeutralLanguage>
		<AssemblyName>SkillTree_IL2cpp</AssemblyName>
		<LangVersion>latest</LangVersion>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

	<ItemGroup>
		<Compile Include="Core\App\SkillTreeApp.cs" />
		<Compile Include="Core\Core.cs" />
		<Compile Include="Core\Effects\BloodRush.cs" />
		<Compile Include="Core\Effects\Ghost.cs" />
		<Compile Include="Core\Patches\Miscellaneous\ContractPatches.cs" />
		<Compile Include="Core\Patches\Miscellaneous\CrossHairPatches.cs" />
		<Compile Include="Core\Patches\Hustler\TrashPatches.cs" />
		<Compile Include="Core\Patches\Hustler\PawnShopPatches.cs" />
		<Compile Include="Core\Patches\Enforcer\PickpocketPatches.cs" />
		<Compile Include="Core\Utilities\ConfigManager.cs" />
		<Compile Include="Core\Serialization\Cooldowns.cs" />
		<Compile Include="Core\Utilities\IconManager.cs" />
		<Compile Include="Core\Patches\Compatibility\SkillTree_EmpirePatches.cs" />
		<Compile Include="Core\Patches\Provisioner\GrowContainerPatches.cs" />
		<Compile Include="Core\Patches\Provisioner\CraftingSpeedPatches.cs" />
		<Compile Include="Core\Patches\Provisioner\MushroomPatches.cs" />
		<Compile Include="Core\Patches\Provisioner\QualityPatches.cs" />
		<Compile Include="Core\Patches\Provisioner\QuantityPatches.cs" />
		<Compile Include="Core\Patches\Provisioner\PlantPatches.cs" />
		<Compile Include="Core\Patches\Special\LaunderingPatches.cs" />
		<Compile Include="Core\Patches\Logistician\SupplierPatches.cs" />
		<Compile Include="Core\Cache.cs" />
		<Compile Include="Core\Patches\Hustler\BusinessPatches.cs" />
		<Compile Include="Core\Patches\Logistician\DealerPatches.cs" />
		<Compile Include="Core\Patches\Hustler\ATMPatches.cs" />
		<Compile Include="Core\Patches\Logistician\BotanistBehaviorPatches.cs" />
		<Compile Include="Core\Patches\Hustler\NPCPatches.cs" />
		<Compile Include="Core\Patches\Hustler\CounterOfferPatches.cs" />
		<Compile Include="Core\Patches\Logistician\DeliveryPatches.cs" />
		<Compile Include="Core\Patches\Enforcer\CrimePatches.cs" />
		<Compile Include="Core\Patches\Enforcer\PlayerPatches.cs" />
		<Compile Include="Core\Patches\Enforcer\XPPatches.cs" />
		<Compile Include="Core\Patches\Enforcer\ItemStackPatches.cs" />
		<Compile Include="Core\Patches\Enforcer\HealthPatches.cs" />
		<Compile Include="Core\Patches\Miscellaneous\ShopPatches.cs" />
		<Compile Include="Core\Skills\Skill.cs" />
		<Compile Include="Core\Skills\SkillCategory.cs" />
		<Compile Include="Core\Skills\SkillModifiers.cs" />
		<Compile Include="Core\Patches\Hustler\CustomerPatches.cs" />
		<Compile Include="Core\Patches\Enforcer\BedPatches.cs" />
		<Compile Include="Core\Serialization\SkillTreeData.cs" />
		<Compile Include="Core\Serialization\KillCounts.cs" />
		<Compile Include="Core\Serialization\SaveManager.cs" />
		<Compile Include="Core\Patches\Special\SkillActive.cs" />
		<Compile Include="Core\Patches\Logistician\EmployeePatches.cs" />
		<Compile Include="Core\Patches\Enforcer\MovementPatches.cs" />
		<Compile Include="Core\Serialization\SkillPoints.cs" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="0Harmony">
	    <HintPath>$(MelonLoaderNet6Dir)\0Harmony.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Assembly-CSharp">
	    <HintPath>$(Il2CppAssembliesDir)\Assembly-CSharp.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppScheduleOne.Core">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppScheduleOne.Core.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppAeLa.EasyFeedback">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppAeLa.EasyFeedback.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppAeLa.EasyFeedback.InputSystemSupport">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppAeLa.EasyFeedback.InputSystemSupport.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppAmplifyImpostors">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppAmplifyImpostors.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppAmplifyImpostors.Runtime">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppAmplifyImpostors.Runtime.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppAstarPathfindingProject">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppAstarPathfindingProject.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppBoxophobic.Utils.Scripts">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppBoxophobic.Utils.Scripts.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppCinemachine">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppCinemachine.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2Cppcom.rlabrecque.steamworks.net">
	    <HintPath>$(Il2CppAssembliesDir)\Il2Cppcom.rlabrecque.steamworks.net.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppCorgiGodRays">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppCorgiGodRays.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppEdgegap">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppEdgegap.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppFishNet.Runtime">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppFishNet.Runtime.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppGameKit.Dependencies">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppGameKit.Dependencies.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppGameKit.Utilities">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppGameKit.Utilities.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppHBAO.Demo.Runtime">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppHBAO.Demo.Runtime.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppHBAO.Demo.Universal.Runtime">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppHBAO.Demo.Universal.Runtime.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppHBAO.Runtime">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppHBAO.Runtime.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppHBAO.Universal.Runtime">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppHBAO.Universal.Runtime.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppHSVPicker">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppHSVPicker.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppInterop.Common">
	    <HintPath>$(MelonLoaderNet6Dir)\Il2CppInterop.Common.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppInterop.Generator">
	    <HintPath>$(MelonLoaderNet6Dir)\Il2CppInterop.Generator.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppInterop.HarmonySupport">
	    <HintPath>$(MelonLoaderNet6Dir)\Il2CppInterop.HarmonySupport.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppInterop.Runtime">
	    <HintPath>$(MelonLoaderNet6Dir)\Il2CppInterop.Runtime.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppLokoSolo.PinchableScrollRect">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppLokoSolo.PinchableScrollRect.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppMono.Posix">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppMono.Posix.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppMono.Security">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppMono.Security.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2Cppmscorlib">
	    <HintPath>$(Il2CppAssembliesDir)\Il2Cppmscorlib.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppNewtonsoft.Json">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppNewtonsoft.Json.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppOokii.Dialogs">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppOokii.Dialogs.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppPathfinding.ClipperLib">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppPathfinding.ClipperLib.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppPathfinding.Ionic.Zip.Reduced">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppPathfinding.Ionic.Zip.Reduced.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppPathfinding.Poly2Tri">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppPathfinding.Poly2Tri.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppRadiantGI">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppRadiantGI.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppRootMotion">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppRootMotion.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppRuntimePreviewGenerator.Runtime">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppRuntimePreviewGenerator.Runtime.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2Cppsc.stylizedgrass.runtime">
	    <HintPath>$(Il2CppAssembliesDir)\Il2Cppsc.stylizedgrass.runtime.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2Cppsc.stylizedwater2.runtime">
	    <HintPath>$(Il2CppAssembliesDir)\Il2Cppsc.stylizedwater2.runtime.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppStylizedWaterForURP">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppStylizedWaterForURP.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppSystem">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppSystem.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppSystem.Configuration">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppSystem.Configuration.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppSystem.Core">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppSystem.Core.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppSystem.Data">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppSystem.Data.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppSystem.Design">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppSystem.Design.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppSystem.Drawing">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppSystem.Drawing.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppSystem.IO.Compression">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppSystem.IO.Compression.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppSystem.IO.Compression.FileSystem">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppSystem.IO.Compression.FileSystem.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppSystem.Net.Http">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppSystem.Net.Http.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppSystem.Numerics">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppSystem.Numerics.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppSystem.Runtime.Serialization">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppSystem.Runtime.Serialization.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppSystem.Security">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppSystem.Security.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppSystem.Windows.Forms">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppSystem.Windows.Forms.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppSystem.Xml">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppSystem.Xml.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppSystem.Xml.Linq">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppSystem.Xml.Linq.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppVisualDesignCafe.Nature">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppVisualDesignCafe.Nature.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppVisualDesignCafe.Packages">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppVisualDesignCafe.Packages.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2CppVisualDesignCafe.ShaderX">
	    <HintPath>$(Il2CppAssembliesDir)\Il2CppVisualDesignCafe.ShaderX.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Il2Cpp__Generated">
	    <HintPath>$(Il2CppAssembliesDir)\Il2Cpp__Generated.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="MelonLoader">
	    <HintPath>$(MelonLoaderNet6Dir)\MelonLoader.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="S1API">
	    <HintPath>$(S1APIDir)\Mods\S1API.Il2Cpp.MelonLoader.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="S1APILoader">
	    <HintPath>$(S1APIDir)\Plugins\S1APILoader.MelonLoader.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Unity.AI.Navigation">
	    <HintPath>$(Il2CppAssembliesDir)\Unity.AI.Navigation.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Unity.Burst">
	    <HintPath>$(Il2CppAssembliesDir)\Unity.Burst.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Unity.Burst.Unsafe">
	    <HintPath>$(Il2CppAssembliesDir)\Unity.Burst.Unsafe.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Unity.Collections">
	    <HintPath>$(Il2CppAssembliesDir)\Unity.Collections.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Unity.Collections.LowLevel.ILSupport">
	    <HintPath>$(Il2CppAssembliesDir)\Unity.Collections.LowLevel.ILSupport.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Unity.InputSystem">
	    <HintPath>$(Il2CppAssembliesDir)\Unity.InputSystem.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Unity.InputSystem.ForUI">
	    <HintPath>$(Il2CppAssembliesDir)\Unity.InputSystem.ForUI.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Unity.Mathematics">
	    <HintPath>$(Il2CppAssembliesDir)\Unity.Mathematics.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Unity.MemoryProfiler">
	    <HintPath>$(Il2CppAssembliesDir)\Unity.MemoryProfiler.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Unity.Postprocessing.Runtime">
	    <HintPath>$(Il2CppAssembliesDir)\Unity.Postprocessing.Runtime.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Unity.RenderPipeline.Universal.ShaderLibrary">
	    <HintPath>$(Il2CppAssembliesDir)\Unity.RenderPipeline.Universal.ShaderLibrary.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Unity.RenderPipelines.Core.Runtime">
	    <HintPath>$(Il2CppAssembliesDir)\Unity.RenderPipelines.Core.Runtime.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Unity.RenderPipelines.Universal.Runtime">
	    <HintPath>$(Il2CppAssembliesDir)\Unity.RenderPipelines.Universal.Runtime.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Unity.Services.Analytics">
	    <HintPath>$(Il2CppAssembliesDir)\Unity.Services.Analytics.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Unity.Services.Core">
	    <HintPath>$(Il2CppAssembliesDir)\Unity.Services.Core.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Unity.Services.Core.Configuration">
	    <HintPath>$(Il2CppAssembliesDir)\Unity.Services.Core.Configuration.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Unity.Services.Core.Device">
	    <HintPath>$(Il2CppAssembliesDir)\Unity.Services.Core.Device.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Unity.Services.Core.Environments.Internal">
	    <HintPath>$(Il2CppAssembliesDir)\Unity.Services.Core.Environments.Internal.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Unity.Services.Core.Internal">
	    <HintPath>$(Il2CppAssembliesDir)\Unity.Services.Core.Internal.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Unity.Services.Core.Registration">
	    <HintPath>$(Il2CppAssembliesDir)\Unity.Services.Core.Registration.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Unity.Services.Core.Scheduler">
	    <HintPath>$(Il2CppAssembliesDir)\Unity.Services.Core.Scheduler.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Unity.Services.Core.Telemetry">
	    <HintPath>$(Il2CppAssembliesDir)\Unity.Services.Core.Telemetry.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Unity.Services.Core.Threading">
	    <HintPath>$(Il2CppAssembliesDir)\Unity.Services.Core.Threading.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Unity.TextMeshPro">
	    <HintPath>$(Il2CppAssembliesDir)\Unity.TextMeshPro.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Unity.Timeline">
	    <HintPath>$(Il2CppAssembliesDir)\Unity.Timeline.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.AccessibilityModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.AccessibilityModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.AIModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.AIModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.AndroidJNIModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.AndroidJNIModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.AnimationModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.AnimationModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.ARModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.ARModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.AssetBundleModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.AssetBundleModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.AudioModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.AudioModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.ClothModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.ClothModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.ContentLoadModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.ContentLoadModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.CoreModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.CoreModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.CrashReportingModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.CrashReportingModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.DirectorModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.DirectorModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.DSPGraphModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.DSPGraphModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.GameCenterModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.GameCenterModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.GIModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.GIModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.GridModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.GridModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.HotReloadModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.HotReloadModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.ImageConversionModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.ImageConversionModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.IMGUIModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.IMGUIModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.InputLegacyModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.InputLegacyModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.InputModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.InputModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.JSONSerializeModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.JSONSerializeModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.LocalizationModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.LocalizationModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.ParticleSystemModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.ParticleSystemModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.PerformanceReportingModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.PerformanceReportingModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.Physics2DModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.Physics2DModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.PhysicsModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.PhysicsModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.ProfilerModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.ProfilerModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.PropertiesModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.PropertiesModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.ScreenCaptureModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.ScreenCaptureModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.SharedInternalsModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.SharedInternalsModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.SpriteMaskModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.SpriteMaskModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.SpriteShapeModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.SpriteShapeModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.StreamingModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.StreamingModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.SubstanceModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.SubstanceModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.SubsystemsModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.SubsystemsModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.TerrainModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.TerrainModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.TerrainPhysicsModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.TerrainPhysicsModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.TextCoreFontEngineModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.TextCoreFontEngineModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.TextCoreTextEngineModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.TextCoreTextEngineModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.TextRenderingModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.TextRenderingModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.TilemapModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.TilemapModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.TLSModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.TLSModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.UI">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.UI.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.UIElementsModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.UIElementsModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.UIModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.UIModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.UmbraModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.UmbraModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.UnityAnalyticsCommonModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.UnityAnalyticsCommonModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.UnityAnalyticsModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.UnityAnalyticsModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.UnityConnectModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.UnityConnectModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.UnityCurlModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.UnityCurlModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.UnityTestProtocolModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.UnityTestProtocolModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.UnityWebRequestAssetBundleModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.UnityWebRequestAssetBundleModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.UnityWebRequestAudioModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.UnityWebRequestAudioModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.UnityWebRequestModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.UnityWebRequestModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.UnityWebRequestTextureModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.UnityWebRequestWWWModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.UnityWebRequestWWWModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.VehiclesModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.VehiclesModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.VFXModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.VFXModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.VideoModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.VideoModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.VRModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.VRModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.WindModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.WindModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="UnityEngine.XRModule">
	    <HintPath>$(Il2CppAssembliesDir)\UnityEngine.XRModule.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Core\Images\Icons\Icon_BenziesDealer.png" />
	  <EmbeddedResource Include="Core\Images\Icons\Icon_BenziesGoon.png" />
	  <EmbeddedResource Include="Core\Images\Icons\Icon_Cash.png" />
	  <EmbeddedResource Include="Core\Images\Icons\Icon_Clock.png" />
	  <EmbeddedResource Include="Core\Images\Icons\Icon_Enforcer.png" />
	  <EmbeddedResource Include="Core\Images\Icons\Icon_Heart.png" />
	  <EmbeddedResource Include="Core\Images\Icons\Icon_Hustler.png" />
	  <EmbeddedResource Include="Core\Images\Icons\Icon_Logistician.png" />
	  <EmbeddedResource Include="Core\Images\Icons\Icon_PoliceOfficer.png" />
	  <EmbeddedResource Include="Core\Images\Icons\Icon_SkillTree_Forked.png" />
	  <EmbeddedResource Include="Core\Images\Icons\Icon_Special.png" />
	  <EmbeddedResource Include="Core\Images\Icons\Icon_Supplier.png" />
	  <EmbeddedResource Include="Core\Images\Icons\Icon_Trashcan.png" />
	  <EmbeddedResource Include="Core\Images\Icons\Icon_WashingMachine.png" />
	</ItemGroup>
</Project>